# Google App Engine Configuration
runtime: java11

instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 1
  target_cpu_utilization: 0.6

env_variables:
  TELEGRAM_BOT_USERNAME: 'your_bot_username'
  TELEGRAM_BOT_TOKEN: 'your_bot_token'

